config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root 'home#index'
  resources :home, only: :index

  resources :collections do
    resources :articles
  end

  post 'collections/:collection_id/articles/:id/archive' => 'articles#archive', as: :archive
  post 'collections/:collection_id/upvote' => 'collections#upvote', as: :collection_upvote
  post 'collections/:collection_id/downvote' => 'collections#downvote', as: :collection_downvote
  post 'collections/:collection_id/articles/:article_id/upvote' => 'articles#upvote', as: :article_upvote
  post 'collections/:collection_id/articles/:article_id/downvote' => 'articles#downvote', as: :article_downvote

  get 'archive', to: 'collections#archive', as: :archived
  post 'collections/:collection_id/articles/:article_id/restore', to: 'articles#restore', as: :restore

  

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :user_collections
  has_many :users, through: :user_collections
  has_many :collection_articles
  has_many :articles, through: :collection_articles

	validates_presence_of :name

  def upvote
    self.priority += 1
    self.save
  end

  def downvote
    self.priority -= 1
    self.save
  end

  def vote_links
    if self.priority < 1
      upvote
    elsif self.priority < 2
      dowvote
    end
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @articles = []
    @collections = current_user.collections
    @collections.each do |col|
      @articles << col.articles.all.order("priority DESC")
    end
    @articles = @articles.flatten.uniq
  end

  def new
    @collection = Collection.new
  end

  def create
    @collection = Collection.new(collection_params)
    if Collection.find_by_name(collection_params[:name])
      flash[:notice] = "#{collection_params[:name]} is already in use"
      render 'new'
    else
      current_user.collections << @collection
      respond_to do |format|
        if @collection.save
          format.html { redirect_to collection_path(@collection), notice: 'Collection was successfully added.' }
        else
          format.html { render action: 'new' }
        end
      end
    end
  end

  def edit
    @collection = Collection.find(params[:id])
  end

  def show
    @collection = Collection.find(params[:id])
    @article = Article.new
    unless current_user.collections.include?(@collection)
      redirect_to collections_path
    end

  end

  def update
    @collection = Collection.find(params[:id])
    respond_to do |format|
      if @collection.update_attributes(collection_params)
        format.html {redirect_to collection_path(@collection), notice: 'Collection was successfully updated.'}
      else
        format.html {render action: 'edit'}
      end
    end
  end

  def destroy
  end

  def archive
    @collections = current_user.collections
  end

  def upvote
    @collection = Collection.find(params[:collection_id])
    @collection.upvote
    redirect_to collections_path, notice: 'Collection was successfully upvoted.'
  end

  def downvote
    @collection = Collection.find(params[:collection_id])
    @collection.downvote
    redirect_to collections_path, notice: 'Collection was successfully downvoted.'
  end

  private
  def collection_params
    params.require(:collection).permit(:name, :id)
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= form_for(@collection) do |f| %>
	<% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/collections/archive.html.erb
<div class='inner-wrapper'>
  <h1>Archive</h1>
</div>
<% @collections.each do |col| %>
<div class='inner-wrapper'>
  <h3><%= col.name %> (<%= col.articles.where(archived: true).count %>)</h3>
  <% col.articles.where(archived: true).each do |article| %>
    <%= link_to article.title, article.linkify, :target => "_blank"%>
    <%= button_to 'Restore', restore_path(col, article) %><br>
  <% end %>
</div>
<% end %>

app/views/collections/edit.html.erb
<div class='inner-wrapper'>
<%= render 'form' %>
</div>

app/views/collections/index.html.erb
<% title "Collections" %>
<div class='inner-wrapper'>
<h2>My Collections <%= link_to '+', new_collection_article_path(current_user.collections.find_by_name('Unsorted')) %></h2>

  <% current_user.collections.each do |col| %>
    <li><%= link_to col.name, col %></li>
  <% end %>

  <% if @articles.count > 0 %>
    <% @articles.each do |article| %>
      <h4><%= link_to article.title, article.linkify, :target => "_blank" %></h4>
      <%= link_to 'Read', collection_article_path(article.collections.first, article) %>
      <h4>Collections: <% article.collections.each do |col| %>
      <%= link_to col.name, collection_path(col) %>
      <% end %></h4>
    <% end %>
  <% end %>
</div>

app/views/collections/new.html.erb
<div class='inner-wrapper'>
<%= render 'form' %>
</div>

app/views/collections/show.html.erb
<div class="banner">
    <h2 class='header'><%= @collection.name %></h2>
    <div class='url-bar'><%= render 'articles/form' %>
    <span id='submit'>next</span>
    </div>

</div>
<div class="l-content">
    <div class="pricing-tables pure-g">
    <% @collection.articles.each do |article|  %>
     <% if !article.archived? %>
        <div class="pure-u-1 pure-u-md-1-3">
            <div class="pricing-table pricing-table-free">

                <div class="pricing-table-header"  style='background: transparent url("<%= article.article_image %>") 0 0 no-repeat;'>
                    <span class="pricing-table-price">
                      <span><%= link_to article.title, article.linkify, :target => "_blank" %></span>
                    </span>
                </div>

                <button class="button-choose">
                  <%= link_to archive_path(@collection, article), method: :post do %>
                    <i class="fa fa-archive"></i><br>
                    archive
                  <% end %>
                </button>

                <button class="button-choose">
                  <%= link_to collection_article_path(@collection, article) do %>
                    <i class="fa fa-search"></i><br>
                    read
                  <% end %>
                </button>

                <button class="button-choose">
                  <%= link_to edit_collection_article_path(@collection, article), method: :get do %>
                    <i class="fa fa-pencil"></i><br>
                    edit
                  <% end %>
                </button>

            </div>
        </div>
    <% end %>
    <% end %>
    </div> <!-- end pricing-tables -->
</div>