config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root 'home#index'
  resources :home, only: :index

  resources :collections do
    resources :articles
  end

  post 'collections/:collection_id/articles/:id/archive' => 'articles#archive', as: :archive
  post 'collections/:collection_id/upvote' => 'collections#upvote', as: :collection_upvote
  post 'collections/:collection_id/downvote' => 'collections#downvote', as: :collection_downvote
  post 'collections/:collection_id/articles/:article_id/upvote' => 'articles#upvote', as: :article_upvote
  post 'collections/:collection_id/articles/:article_id/downvote' => 'articles#downvote', as: :article_downvote

  get 'archive', to: 'collections#archive', as: :archived
  post 'collections/:collection_id/articles/:article_id/restore', to: 'articles#restore', as: :restore

  

end

app/views/layouts/_navbar.html.erb
<header>
  <div class="home-menu pure-menu pure-menu-open pure-menu-horizontal pure-menu-fixed">
    <a href="/" class="pure-menu-heading">Parascope</a>
    <ul id='controls'>
      <% if user_signed_in? %>
        <li class="pure-menu-selected">
            <a href="#">collections</a>
            <ul id='dropdown'>
                <li ><%= link_to 'Add New', new_collection_path %></li>
                <li class="pure-menu-separator"></li>
                <% current_user.collections.each do |col| %>
                  <% if col.name == 'Unsorted' %>
                    <li class="pure-menu-open"><%= link_to 'unsorted', collection_path(col) %><li>
                  <% else %>
                    <li><%= link_to col.name, collection_path(col) %><li>
                  <% end %>
                <% end %>
            </ul>
        </li>
        <li><%= link_to 'archive', archived_path %></li>
      <li><%= link_to "profile", edit_user_registration_path%></li>
      <li><%= link_to 'x', destroy_user_session_path, :method => :delete %></li>
      <% else %>
       <li><%= link_to "Sign Up", new_user_registration_path %></li>
       <li><%= link_to "Log In", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>

<!--/.nav-collapse -->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Parascope</title>
  <script src="http://yui.yahooapis.com/3.17.2/build/yui/yui-min.js"></script>
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lte IE 8]>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-old-ie-min.css">
<![endif]-->
<!--[if gt IE 8]><!-->
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-min.css">
<!--<![endif]-->

</head>

<body>

  <%= render 'layouts/navbar' %>

<div class='wrapper'>
  <% if notice %>
  <%= notice %>
  <% end %>
  <%= yield %>
</div>

</body>
</html>